#  ███████╗███████╗███████╗██╗  ██╗     ██████╗ ██████╗ ███╗   ██╗███████╗██╗ ██████╗ 
#  ██╔════╝██╔════╝██╔════╝██║  ██║    ██╔════╝██╔═══██╗████╗  ██║██╔════╝██║██╔════╝ 
#  ███████╗█████╗  ███████╗███████║    ██║     ██║   ██║██╔██╗ ██║█████╗  ██║██║  ███╗
#  ╚════██║██╔══╝  ╚════██║██╔══██║    ██║     ██║   ██║██║╚██╗██║██╔══╝  ██║██║   ██║
#  ███████║███████╗███████║██║  ██║    ╚██████╗╚██████╔╝██║ ╚████║██║     ██║╚██████╔╝
#  ╚══════╝╚══════╝╚══════╝╚═╝  ╚═╝     ╚═════╝ ╚═════╝ ╚═╝  ╚═══╝╚═╝     ╚═╝     ╚═════╝ 
#
#  Smart session manager for the terminal
#  https://github.com/joshmedeski/sesh

# import = ["~/.config/sesh/configs/nu-sesh.toml"]
#:schema https://github.com/joshmedeski/sesh/raw/main/sesh.schema.json
blacklist = ["scratch"]

# Introduces a caching layer in order to speed up load times
cache = false

# Makes it aware of the separators
separator_aware = true

# Displays parent directory
dir_length = 2

[tui]
show_icons = true

[default_session]
startup_command = "nvim -c 'lua Snacks.picker.files()'"
startup_command_ignore_dirs = ["${DEVELOPMENT_DIR:-~/development}", "~/.config"]
preview_command = "eza --all --git --icons --color=always {}"

[[wildcard]]
pattern = "${DEVELOPMENT_DIR:-~/development}/*"
startup_command = "nvim"

[[wildcard]]
pattern = "~/.config/*"
startup_command = "nvim"
preview_command = "bat --color=always --style=numbers --line-range=:40 {}"

[[session]]
name = "ghostty config"
path = "~/.config/ghostty"
startup_command = "nvim config"

[[session]]
name = "sesh config"
path = "~/.config/sesh"
startup_command = "nvim sesh.toml"

[[session]]
name = "dotfiles"
path = "${DEVELOPMENT_DIR:-~/development}/dotfiles_new"
startup_command = "nvim"

